blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('photo/upload/', views.photo_upload, name='photo_upload'),
    path('photo/<int:photo_id>/', views.view_photo, name='view_photo'),
    path('photo/<int:photo_id>/edit/', views.edit_photo, name='edit_photo'),
    path('photo/<int:photo_id>/delete/', views.delete_photo, name='delete_photo'),
    path('comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('blog/<int:blog_id>/edit/', views.edit_blog, name='edit_blog'),
    path('creator-dashboard/', views.creator_dashboard, name='creator_dashboard'),

    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/users/', views.admin_users, name='admin_users'),
    path('admin-panel/users/delete/<int:user_id>/', views.admin_delete_user, name='admin_delete_user'),
    path('admin-panel/photos/', views.admin_photos, name='admin_photos'),
    path('admin-panel/photos/delete/<int:photo_id>/', views.admin_delete_photo, name='admin_delete_photo'),
    path('admin-panel/blogs/', views.admin_blogs, name='admin_blogs'),
    path('admin-panel/blogs/delete/<int:blog_id>/', views.admin_delete_blog, name='admin_delete_blog'),
    path('admin-panel/categories/', views.admin_categories, name='admin_categories'),
    path('admin-panel/categories/add/', views.admin_add_category, name='admin_add_category'),
    path('admin-panel/categories/edit/<int:cat_id>/', views.admin_edit_category, name='admin_edit_category'),
    path('admin-panel/categories/delete/<int:cat_id>/', views.admin_delete_category, name='admin_delete_category'),
    path('blog/create/', views.blog_and_photo_upload, name='blog_and_photo_upload'),

]

fotoblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView)
from django.urls import path, include

import authentication.views
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('', blog.views.home, name='home'),
    path('photo-feed/', blog.views.photo_feed, name='photo_feed'),
    path('blog-feed/', blog.views.blog_feed, name='blog_feed'),

    path('login/', LoginView.as_view(
            template_name='authentication/login.html',
            redirect_authenticated_user=True),
        name='login'),

    path('change-password/', PasswordChangeView.as_view(
        template_name='authentication/Cmdp.html'),
         name='password_change'
         ),
    path('change-password-done/', PasswordChangeDoneView.as_view(
        template_name='authentication/CmdpA.html'),
         name='password_change_done'
         ),

    path('signup/', authentication.views.signup_page, name='signup'),
    path('profile-photo/upload', authentication.views.upload_profile_photo, name='upload_profile_photo'),
    path('blog/create', blog.views.blog_and_photo_upload, name='blog_create'),
    path('blog/<int:blog_id>', blog.views.view_blog, name='view_blog'),
    path('photo/upload-multiple/', blog.views.create_multiple_photos, name='create_multiple_photos'),
    path('follow-users/', blog.views.follow_users, name='follow_users'),
    path('about-us/', blog.views.about, name='about'),
    path('contact/', blog.views.contact_view, name='contact'),
    path('auth/', include('authentication.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#  les images stockées dans le répertoire MEDIA_ROOT seront servies au chemin donné par MEDIA_URL.

blog/models.py
from django.conf import settings
from django.db import models
from PIL import Image
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class Categorie(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')

    def __str__(self):
        return self.name


class Photo(models.Model):
    image = models.ImageField(verbose_name='image')
    caption = models.CharField(max_length=128, blank=True, verbose_name='légende')
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Categorie, related_name='photos', blank=True, verbose_name="Catégories")
    date_created = models.DateTimeField(auto_now_add=True)

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

    def __str__(self):
        return f'{self.caption}'


class Blog(models.Model):
    photo = models.ForeignKey('Photo', null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128, verbose_name='titre')
    content = models.CharField(max_length=5000, verbose_name='contenu')
    categories = models.ManyToManyField(Categorie, related_name='blogs', blank=True, verbose_name="Catégories")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blogs') 
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')

    def _get_word_count(self):
        return len(self.content.split(' '))

    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'


class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)
    
    class Meta:
        unique_together = ('contributor', 'blog')



class Commentaire(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    text = models.TextField("Commentaire")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Commentaire de {self.user} sur {self.content_object}"

templates/base.html
{% load static %}
<html>
  <head>
    <title>Blog photo</title>

    <link rel="stylesheet" href="{% static 'style/style.css' %}" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <nav class="navbar navbar-expand-lg bg-white shadow-sm">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold text-primary" href="{% url 'home' %}">PhotoBlog</a>
  
      <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav gap-2">
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'admin_panel' %}">Admin</a>
          </li>
          {% endif %}
          <li class="nav-item"><a class="nav-link text-dark" href="{% url 'home' %}">Accueil</a></li>
          {% if user.is_authenticated %}
          {% if request.user.is_authenticated and request.user.role == "CREATOR" %}
          <li class="nav-item"><a class="nav-link text-dark" href="{% url 'creator_dashboard' %}">🎨 Mon tableau de bord</a></li>
          {% endif %}
          <li class="nav-item"><a class="nav-link text-dark" href="{% url 'photo_feed' %}">Flux de photos</a></li>
          <li class="nav-item"><a class="nav-link text-dark" href="{% url 'blog_feed' %}">Flux de blogs</a></li>
          {% endif %}
          <li class="nav-item"><a class="nav-link text-dark" href="{% url 'about' %}">À propos</a></li>
          <li class="nav-item"><a class="nav-link text-dark" href="{% url 'contact' %}">Contact</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'logout' %}">Se déconnecter</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-primary" href="{% url 'login' %}">Se connecter</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
   
    
    <div class="sidebar">
      <h1><a href="{% url 'home' %}" style="text-decoration: none; color: inherit;">Photo blog</a></h1>
      {% if user.is_authenticated %}
      <p>Salut, "{{ user }}" -ʕ•̫͡•ʔ•̫͡•ཻʕ•̫͡•ʔ•͓͡•ʔ-</p>
      {% if user.profile_photo %}
      <img
        class="avatar"
        src="{{ user.profile_photo.url }}"
        alt="Profile Photo"
      />
      {% else %}
      <img
        class="avatar"
        src="{% static 'image/default_profile.png' %}"
        alt="Default Profile Photo"
      />
      {% endif %}
      <p><a href="{% url 'home' %}">Accueil</a></p>
      <p><a href="{% url 'follow_users' %}">Suivre des utilisateurs</a></p>
      {% if perms.blog.add_blog %}
      <p><a href="{% url 'blog_create' %}">Écrire un blog</a></p>
      {% endif %} {% if perms.blog.add_photo %}
      <p><a href="{% url 'photo_upload' %}">Télécharger une photo</a></p>
      <p>
        <a href="{% url 'create_multiple_photos' %}"
          >Télécharger plusieurs photos</a
        >
      </p>
      {% endif %}
      <p>
        <a href="{% url 'upload_profile_photo' %}"
          >Changer la photo de profil</a
        >
      </p>
      <p><a href="{% url 'password_change' %}">Changer le mot de passe</a></p>
      <p><a href="{% url 'logout' %}">Se déconnecter</a></p>
      {% else %}
      <div id="dynamic-content"></div>
      <script>
        document.addEventListener("DOMContentLoaded", function () {
          var images = [
            "{% static 'image/default_profile.png' %}",
            "{% static 'image/4.jpg' %}",
            "{% static 'image/5.jpg' %}",
            "{% static 'image/6.jpg' %}",
            "{% static 'image/7.jpg' %}",
            "{% static 'image/Tan.jpg' %}",
            "{% static 'image/2.jpeg' %}",
            "{% static 'image/3.jpg' %}",
          ];
          var randomImage = images[Math.floor(Math.random() * images.length)];
          var imgElement = document.createElement("img");
          imgElement.src = randomImage;
          imgElement.alt = "Random Photo";
          imgElement.style.width = "100%";
          document.getElementById("dynamic-content").appendChild(imgElement);
        });
      </script>
      {% endif %}
    </div>
    <div class="main">{% block content %}{% endblock content %}</div>
  </body>
</html>